# Generated by Django 2.2.7 on 2019-11-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField()),
                ('pregunta', models.TextField()),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('tiempo',),
            },
        ),
    ]
